# The Cupcake GUI Toolkit Backends Top-Level Makefile
# (c) Kristian Klomsten Skordal 2012 <kristian.skordal@gmail.com>
# Report bugs and issues on <http://github.com/skordal/cupcake/issues>
include ../../config.mk

.PHONY: all cairo clean

all: cairo

clean:
	-$(MAKE) -C cairo clean

cairo:
	$(MAKE) -C cairo all

